#POST localhost:8083/api/projects
POST 10.220.222.62:8081/api/projects
Content-Type: application/json

{
  "projectName": "testProject",
  "memberId": "ss"
}

###
GET localhost:8083/api/projects/13
###

GET localhost:8083/api/projects/admin/list

###

GET localhost:8083/api/projects/14

###
GET localhost:8081/api/members/20/16
###

POST

###


GET localhost:8083/api/projects/13

###

PUT localhost:8081/api/projects
Content-Type: application/json

{
  "projectId": 1,
  "status": "111줭"
}

###

GET 10.220.222.62:8081/api/projects/13
###

#POST 10.220.222.62:8081/api/members/register
POST localhost:8083/api/members/register
Content-Type: application/json

{
  "memberId" : "reeeee",
  "projectId" : 13,
  "memberRole" : "가나다라마바사아x자차"
}

###

GET localhost:8083/api/members/admin/13

###

POST localhost:8083/api/milestones
Content-Type: application/json

{
  "projectId" : 13,
  "milestoneStatus" : "pass"
}

###

PUT localhost:8083/api/milestones/6
Content-Type: application/json

{
  "mileStoneStatus" : "update"
}

###

GET localhost:8083/api/milestones/13

###

DELETE localhost:8083/api/milestones/5

###

POST localhost:8083/api/tags
Content-Type: application/json

{
  "tagName": "positive2",
  "projectId": 13
}

###

GET localhost:8081/api/tags/13

###
GET 10.220.222.62:8081/api/tags/1

###
PUT  localhost:8083/api/tags/2
Content-Type: application/json

{
  "tagName" : "update"
}

###

DELETE  localhost:8083/api/tags/1


###

POST localhost:8083/api/task
Content-Type: application/json

{
  "taskTitle": "title",
  "taskContent": "content",
  "projectId": 13
}

###
DELETE localhost:8083/api/tasks/1
###
#PUT localhost:8083/api/tasks/2
#Content-Type: application/json

###
GET localhost:8083/api/tasks/13


###

POST localhost:8083/api/tasks
Content-Type: application/json

{
  "taskTitle" : "sadfasdfasdf",
  "taskContent": "content",
  "projectId": 13,
  "milestoneId": 12,
  "tagId": []
}

###

DELETE localhost:8083/api/tasks/1

###
GET localhost:8083/api/projects/tasks/14

###

PUT 10.220.222.62:8081/api/tasks/44
Content-Type: application/json

{
  "taskContent" : "변경?",
  "milestoneId" :12,
  "tagId" : [4]
}

###

GET localhost:8083/api/task/tag/44

###

POST localhost:8083/api/comments
Content-Type: application/json
Accept: application/json

{
  "content" : "",
  "taskId" : 25,
  "memberId" : "admin",
  "projectId" : 14
}

###

GET localhost:8083/api/comments/25
Accept: application/json

###

GET localhost:8083/api/comment/5
Accept: application/json

###

PUT localhost:8083/api/comments/5 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "commentContent" : "test??"
}