POST localhost:8083/api/projects
Content-Type: application/json

{
  "projectName": "testProject",
  "memberId": "testId"
}

###
GET 10.220.222.62:8081/api/projects/1
###

GET 10.220.222.62:8081/api/projects/hello/list

###
GET 10.220.222.62:8081/api/members/13
###

GET localhost:8083/api/members/1

###

GET localhost:8083/api/projects/13

###

PUT localhost:8081/api/projects
Content-Type: application/json

{
  "projectId": 1,
  "status": "111줭"
}

###

#POST 10.220.222.62:8081/api/members/register
POST localhost:8083/api/members/register
Content-Type: application/json

{
  "memberId" : "aello",
  "projectId" : 13,
  "memberRole" : "MEMBER"
}

###

GET localhost:8083/api/members/admin/13

###

POST localhost:8083/api/milestones
Content-Type: application/json

{
  "projectId" : 13,
  "milestoneStatus" : "pass"
}

###

PUT localhost:8083/api/milestones/1
Content-Type: application/json

{
  "mileStoneStatus" : "update"
}

###

GET localhost:8083/api/milestones/13

###

DELETE localhost:8083/api/milestones/5

###

POST localhost:8083/api/tags
Content-Type: application/json

{
  "tagName": "positive2",
  "projectId": 13
}

###

GET localhost:8083/api/tags/13

###
GET 10.220.222.62:8081/api/tags/1

###
PUT  localhost:8083/api/tags/2
Content-Type: application/json

{
  "tagName" : "update"
}

###

DELETE  localhost:8083/api/tags/1


###

POST localhost:8083/api/task
Content-Type: application/json

{
  "taskTitle": "title",
  "taskContent": "content",
  "projectId": 13
}

###
DELETE localhost:8083/api/tasks/1
###
#PUT localhost:8083/api/tasks/2
#Content-Type: application/json

###
GET localhost:8083/api/tasks/13


###

POST localhost:8083/api/tasks
Content-Type: application/json

{
  "taskTitle" : "sadfasdfasdf",
  "taskContent": "content",
  "projectId": 13,
  "milestoneId": 12,
  "tagId": [2, 3]
}

###

DELETE localhost:8083/api/tasks/41

###
GET localhost:8083/api/projects/tasks/1

###

PUT localhost:8083/api/tasks/42
Content-Type: application/json

{
  "taskContent" : "변경?",
  "milestoneId" :12,
  "tagId" : null
}